export const CHANGE_MODE = "CHANGE_MODE"
export const SET_SELECTED_SHAPES = "SET_SELECTED_SHAPES"
export const SET_EDITED_SHAPE = "SET_EDITED_SHAPE"

export const CHANGE_ACTIVE_DOC_ID = "CHANGE_ACTIVE_DOC_ID"
export const CHANGE_EDITOR_DOCUMENT = "CHANGE_EDITOR_DOCUMENT"
export const CHANGE_DOCUMENT_TITLE = "CHANGE_DOCUMENT_TITLE"


export const OPEN_DOCUMENT = "OPEN_DOCUMENT"
export const UNDO = "UNDO"
export const REDO = "REDO"
export const CREATE_DOCUMENT = "CREATE_DOCUMENT"
