export const CHANGE_MODE = "CHANGE_MODE"
export const UNDO = "UNDO"
export const MOVE_VERTEX = "MOVE_VERTEX"
export const SET_SELECTED_SHAPES = "SET_SELECTED_SHAPES"
export const CHANGE_ACTIVE_DOC_ID = 'CHANGE_ACTIVE_DOC_ID';
