GET http://localhost:8000/api/documents

###


GET http://localhost:8000/api/documents/5cfa9dd1ea451113d8fd6b0a

###

POST http://localhost:8000/api/documents
Content-Type: application/json

{
    "key": "my-dev-value"
}

###

DELETE http://localhost:8000/api/documents/5cfd265ab4cc612fa4aaa933

###

PUT http://localhost:8000/api/documents/4f8f3abb-6ec3-44c6-b51a-724a799e77b1
{}

###