GET http://localhost:9000/api/documents

###


GET http://localhost:9000/api/documents/5d13a49ce077411bc77773f3

###

POST http://localhost:9000/api/documents
Content-Type: application/json

{
    "title": "new Document"
}

###

DELETE http://localhost:9000/api/documents/5d13a4885fe62d1bb9ee26e6

###

PUT http://localhost:9000/api/documents/5d13a457a0ba051bad0a8e92
Content-Type: application/json

{
  "title": "Changed title"
}

###
