export const CHANGE_MODE = "CHANGE_MODE"
export const SET_SELECTED_SHAPES = "SET_SELECTED_SHAPES"
export const SET_EDITED_SHAPE = "SET_EDITED_SHAPE"

export const CHANGE_ACTIVE_DOC_ID = "CHANGE_ACTIVE_DOC_ID"
export const CHANGE_EDITOR_DOCUMENT_SUCCESS = "CHANGE_EDITOR_DOCUMENT_SUCCESS"
export const OPEN_DOCUMENT = "OPEN_DOCUMENT"

export const UNDO = "UNDO"
export const REDO = "REDO"

// fetching actions
export const RECEIVE_DOCUMENTS_SUCCESS = "RECEIVE_DOCUMENTS_SUCCESS"
export const RECEIVE_DOCUMENTS_ERROR = "RECEIVE_DOCUMENTS_ERROR"
export const CREATE_DOCUMENT_SUCCESS = "CREATE_DOCUMENT_SUCCESS"
export const REQUEST_DOCS = "REQUEST_DOCS"
export const REMOVE_DOC_SUCCESS = "REMOVE_DOC_SUCCESS"

export const REQUEST_DOC_BY_ID_START = "REQUEST_DOC_BY_ID_START"
export const REQUEST_DOC_BY_ID_SUCCESS = "REQUEST_DOC_BY_ID_SUCCESS"
export const REQUEST_DOC_BY_ID_ERROR = "REQUEST_DOC_BY_ID_ERROR"
